# Generated by Django 5.1.7 on 2025-05-16 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ジャンル名')),
                ('description', models.TextField(blank=True, verbose_name='ジャンル説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ジャンル',
                'verbose_name_plural': 'ジャンル',
            },
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='サブジャンル名')),
                ('description', models.TextField(blank=True, verbose_name='サブジャンル説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'サブジャンル',
                'verbose_name_plural': 'サブジャンル',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('description', models.TextField(blank=True, verbose_name='タグ説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('title_kana', models.CharField(blank=True, max_length=200, verbose_name='タイトルふりがな')),
                ('short_title', models.CharField(blank=True, max_length=50, verbose_name='タイトル略称')),
                ('content', models.TextField(blank=True, verbose_name='概要')),
                ('season', models.PositiveIntegerField(verbose_name='シーズン')),
                ('air_date', models.DateField(verbose_name='放送')),
                ('website', models.URLField(blank=True, verbose_name='公式サイト')),
                ('source_website', models.URLField(blank=True, verbose_name='ソース')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='titles.genre', verbose_name='ジャンル')),
                ('related_titles', models.ManyToManyField(blank=True, to='titles.title', verbose_name='関連タイトル')),
                ('sub_genre', models.ManyToManyField(blank=True, to='titles.subgenre', verbose_name='サブジャンル')),
                ('tags', models.ManyToManyField(blank=True, to='titles.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'タイトル',
                'verbose_name_plural': 'タイトル',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_title', models.CharField(blank=True, max_length=200, verbose_name='エピソードタイトル')),
                ('episode_number', models.PositiveIntegerField(verbose_name='エピソード番号')),
                ('content', models.TextField(blank=True, verbose_name='概要')),
                ('air_date', models.DateTimeField(verbose_name='放送')),
                ('duration', models.PositiveIntegerField(verbose_name='時間')),
                ('website', models.URLField(blank=True, verbose_name='公式サイト')),
                ('source_website', models.URLField(blank=True, verbose_name='ソース')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='titles.tag', verbose_name='タグ')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='titles.title', verbose_name='タイトル')),
            ],
            options={
                'verbose_name': 'エピソード',
                'verbose_name_plural': 'エピソード',
            },
        ),
    ]
