# Generated by Django 5.1.7 on 2025-05-16 13:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='視聴方法')),
                ('description', models.TextField(blank=True, verbose_name='視聴方法説明')),
                ('website', models.URLField(blank=True, verbose_name='公式サイト')),
                ('search_url', models.URLField(blank=True, verbose_name='検索URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '視聴方法',
                'verbose_name_plural': '視聴方法',
            },
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='リスト名')),
                ('description', models.TextField(blank=True, verbose_name='リスト説明')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='titles.tag', verbose_name='タグ')),
                ('titles', models.ManyToManyField(blank=True, to='titles.title', verbose_name='タイトル')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'マイリスト',
                'verbose_name_plural': 'マイリスト',
            },
        ),
        migrations.CreateModel(
            name='EpisodeWatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_title', models.CharField(blank=True, max_length=200, verbose_name='コメントタイトル')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('watched_date', models.DateField(blank=True, null=True, verbose_name='視聴日')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='評価')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='ネタバレ')),
                ('status', models.CharField(blank=True, choices=[('watched', '視聴済み'), ('watching', '視聴中'), ('not_watched', '未視聴'), ('dropped', '視聴中断')], max_length=20, verbose_name='視聴状況')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='titles.episode', verbose_name='エピソード')),
                ('tags', models.ManyToManyField(blank=True, to='titles.tag', verbose_name='タグ')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('watch_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.watchmethod', verbose_name='視聴方法')),
            ],
            options={
                'verbose_name': 'エピソード視聴記録',
                'verbose_name_plural': 'エピソード視聴記録',
            },
        ),
        migrations.CreateModel(
            name='WatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_title', models.CharField(blank=True, max_length=200, verbose_name='コメントタイトル')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('watched_date', models.DateField(blank=True, null=True, verbose_name='視聴日')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='評価')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='ネタバレ')),
                ('status', models.CharField(blank=True, choices=[('watched', '視聴済み'), ('watching', '視聴中'), ('not_watched', '未視聴'), ('dropped', '視聴中断')], max_length=20, verbose_name='視聴状況')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='titles.tag', verbose_name='タグ')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='titles.title', verbose_name='タイトル')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('watch_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.watchmethod', verbose_name='視聴方法')),
            ],
            options={
                'verbose_name': '視聴記録',
                'verbose_name_plural': '視聴記録',
            },
        ),
    ]
